name: testexo1
on: [push]
jobs:
   run:
     runs-on: ubuntu-latest
     steps:
     - uses: iterative/setup-cml@v1
     - uses: actions/checkout@v3
       with:
         ref: ${{ github.event.pull_request.head.sha }}
     - uses: actions/setup-python@v3
       with:
         python-version: '3.10'
     - uses: py-actions/py-dependency-install@v4
       with:
         path: "requirements.txt"
     - name: Test
       env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       run: |
          pip install --upgrade pip
          python train.py
          
          echo './feature_importance.png' >> report.md
          cml comment create report.md
